checkout-after/config/routes.rb
Checkout::Application.routes.draw do
  resources :orders
  root to: 'orders#index'
end

checkout-after/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessor :card_number, :card_expires_on
  attr_accessible :amount, :card_last_four, :number, :card_number, :card_expires_on

  def purchase
    self.card_last_four = card_number.to_s[-4, 4]
    save!
  end
end

checkout-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

checkout-after/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    # sleep 1
    @orders = Order.page(params[:page]).per_page(10)
  end

  def new
    @order = Order.new(amount: 19.99)
  end

  def create
    @order = Order.new(params[:order])
    @order.purchase
    redirect_to orders_url, notice: "Order created."
  end
end

checkout-after/app/helpers/application_helper.rb
module ApplicationHelper
end

checkout-after/app/helpers/orders_helper.rb
module OrdersHelper
end

checkout-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orders</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

checkout-after/app/views/orders/_order.html.erb
<h2>Order #<%= order.number %></h2>
Amount: <%= number_to_currency(order.amount) %> |
Last Four: <%= order.card_last_four %>

checkout-after/app/views/orders/index.html.erb
<h1>Orders</h1>

<p><%= link_to 'New Order', new_order_path %></p>

<div id="orders">
  <%= render @orders %>
</div>

<%= will_paginate @orders %>

checkout-after/app/views/orders/index.js.erb
$('#orders').append('<%= j render(@orders) %>');
<% if @orders.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@orders) %>');
<% else %>
  $('.pagination').remove();
<% end %>

checkout-after/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for @order do |f| %>
  <div class="field">
    <%= f.label :card_number, "Credit Card Number" %><br />
    <%= f.text_field :card_number %>
    <span class="error"></span>
  </div>
  <div class="field">
    <%= f.label :card_expires_on, "Credit Card Expiration" %><br />
    <%= f.date_select :card_expires_on, add_month_numbers: true, start_year: Time.now.year, order: [:month, :year] %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount, size: 10 %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

checkout-after/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @order.number %>
</p>

<p>
  <b>Card last four:</b>
  <%= @order.card_last_four %>
</p>

<p>
  <b>Amount:</b>
  <%= @order.amount %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>